Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TiendaMarvel.Models;
using TiendaMarvel.Services;

namespace TiendaMarvel.Controllers
{
    public class CarritoController : Controller
    {
        private readonly CarritoService carrito;
        IPedidosRepository pedidos;
        public CarritoController(CarritoService carrito){
            this.carrito = carrito;
            pedidos =  new AzurePedidosRepository();
        }
        // GET: Carrito
        public ActionResult Index()
        {
           var model = carrito.Contenido;
            return View(model);
        }
        public ActionResult Resumen()
        {
           var model = carrito.Contenido;
            return View(model);
        }
        public ActionResult ProcesoPago()
        {
           var model = carrito.Contenido;
            return View(model);
        }
        public ActionResult Ticket()
        {
           var model = carrito.Contenido;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Agregar(PartidaEnCarrito partida){
            //Add something
            await carrito.AgregarPartida(partida);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Quitar(PartidaEnCarrito partida){
            await carrito.QuitarPartida(partida);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Aumentar(PartidaEnCarrito partida){
            await carrito.QuitarPartida(partida);
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<IActionResult> Vaciar(){
            await carrito.VaciarCarrito();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> VaciarPago(){
            await carrito.VaciarCarrito();
            return RedirectToAction(nameof(Index));
        }

        
        [HttpPost]
        public async Task<IActionResult> Pagar(PedidoModel pedido){
            
            await carrito.Pagar(pedido);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using TiendaMarvel.Models;
using TiendaMarvel.Repositories;

namespace TiendaMarvel.Controllers
{
    public class CatalogoController : Controller
    {
        // GET: Catalogo
        IProductosRepository productos;
        private IApplicationBuilder app;

        public CatalogoController()
        {
            productos =  new AzureProductosRepository();
        } 
        public async Task<ActionResult> Index()
        {
            var model = (await productos.TodosLosProductos())
                    .Select( p => new ProductoModel(){
                        id = p.Codigo,
                        Descripcion = p.Descripcion,
                        Nombre = p.Nombre,
                        Precio = p.Precio,
                        PrecioImpuesto = p.PrecioImpuesto,
                        Categoria = p.Categoria,
                        Imagen = p.ImagenURL
                    });

            return View(model);
        }

        [HttpGet("/products/{id}", Name = "Products_List")]
        public async Task<ActionResult> ProductosPorCategoria(string id)
        {
            

            var model = (await productos.ProductosPorCategoria(id))
                    .Select( p => new ProductoEntity(){
                        Codigo = p.Codigo,
                        Descripcion = p.Descripcion,
                        Nombre = p.Nombre,
                        Precio = p.Precio,
                        PrecioImpuesto = p.PrecioImpuesto,
                        Categoria = p.Categoria,
                        ImagenURL = p.ImagenURL
                    });

            return View(model);
        }

        public async Task<IEnumerable<ProductoModel>> GetAllCategoria(string id)
        {
            var model = (await productos.ProductosPorCategoria(id))
                    .Select( p => new ProductoModel(){
                        id = p.Codigo,
                        Nombre = p.Nombre,
                        Descripcion = p.Descripcion,
                        Categoria = p.Categoria,
                        Precio = p.Precio,
                        PrecioImpuesto = p.PrecioImpuesto,
                        Imagen = p.ImagenURL
                    });
            return model;
        }


        public async Task<ActionResult> Details(string id)
        {
            var model = await productos.LeerProducto(id);
            return View(new ProductoDetalleModel(){
                id = model.Codigo,
                Nombre = model.Nombre,
                Precio = model.Precio,
                PrecioImpuesto = model.PrecioImpuesto,
                Descripcion = model.Descripcion,
                Categoria = model.Categoria,
                Imagen=model.ImagenURL
            });

        }
        

        // GET: Catalogo/Create
        public ActionResult Create()
        {
            var model =  new ProductoCrearModel();
            return View(model);
        }

        // POST: Catalogo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductoCrearModel model)
        {
            if(ModelState.IsValid){
                try
                {
                    // TODO: Add insert logic here

                    await productos.CrearProducto(new ProductoEntity(){
                            Codigo = model.id,
                            Nombre = model.Nombre,
                            Descripcion = model.Descripcion,
                            Categoria=model.Categoria,
                            Precio = model.Precio            
                        });
                        return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        // GET: Catalogo/Details/5
        
        // GET: Catalogo/Edit/5
        public async Task <ActionResult> Edit(string id)
        {
            var producto = await productos.LeerProducto(id);


            return View(new ProductoEditarModel(){
                id = producto.Codigo,
                Nombre = producto.Nombre,
                Precio = producto.Precio,
                Descripcion = producto.Descripcion,
                Categoria = producto.Categoria
            });
        }

        // POST: Catalogo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductoEditarModel model)
        {
            if(ModelState.IsValid){
                try
                {
                    // TODO: Add update logic here
                    await productos.ActualizarDatos(new ProductoEntity(){
                        Codigo = model.id,
                        Nombre = model.Nombre,
                        Precio = model.Precio,
                        Descripcion = model.Descripcion,
                        Categoria = model.Categoria
                    });

                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        public async Task<ActionResult> CambiarImagen(string id){
            var producto =  await productos.LeerProducto(id);

            return View(new ProductoCambiarImagenModel(){
                id = producto.Codigo,
                Nombre = producto.Nombre,
                Imagen =  producto.ImagenURL
        
            });
        }
        [HttpPost]
        public async Task<ActionResult> CambiarImagen(ProductoCambiarImagenModel model){
           
            var p=await productos.LeerProducto(model.id);

            if(p ==null){
                return NotFound();
            }

            if(!ModelState.IsValid){
                return View(model);
            }
            if(model.NuevaImagen.ContentType == "imagen/jpeg"){
                ModelState.AddModelError("NuevaImagen","Solo se aceptan archivos jpeg");
            }
            if(model.NuevaImagen.Length > 10 * 1024 * 1024){
                ModelState.AddModelError("NuevaImagen","Tamaño de la imagen muy grande");
            }
            if(!ModelState.IsValid){
                return View(model);
            }
            
            var res= await productos.ActualizarImagen(p, model.NuevaImagen);
            return RedirectToAction("index");
            
        }
        // GET: Catalogo/Delete/5
        public async Task< ActionResult> Delete(string id)
        {
            var producto = await productos.LeerProducto(id);


            return View(new ProductoBorrarModel(){
                id = producto.Codigo,
                Nombre = producto.Nombre
            });
        }

        // POST: Catalogo/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                await productos.BorrarProducto(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/SolicitarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Newtonsoft.Json;
using TiendaMarvel.Models;
using TiendaMarvel.Repositories;
using TiendaMarvel.Services;

namespace TiendaMarvel.Controllers
{
    public class SolicitarController : Controller
    {
        // GET: Catalogo
        IPedidosRepository pedidos;
        private IApplicationBuilder app;

        public SolicitarController()
        {
            pedidos =  new AzurePedidosRepository();
        } 

        public ActionResult Referencia(string id)
        {
           return View();
        }
        public async Task<ActionResult> Index()
        {
            var model = (await pedidos.LeerPedidosPagados())
                    .Select( p => new PedidoModel(){
                        PedidoId = p.PedidoId,
                        CorreoElectronico = p.CorreoElectronico,
                        FechaPedido = p.FechaPedido,
                        Referencia = p.Referencia,
                        Estado = p.Estado,
                        Productos = p.Productos
                    });

            return View(model);
        }
        public async Task<ActionResult> IndexCliente(string cliente)
        {
            var userID = User.Identity.Name;
            //string sessionID =  HttpContext.Session.ToString();
            var model = (await pedidos.LeerPedidosCliente(userID))
                    .Select( p => new PedidoModel(){
                        PedidoId = p.PedidoId,
                        CorreoElectronico = p.CorreoElectronico,
                        FechaPedido = p.FechaPedido,
                        Referencia = p.Referencia,
                        Estado = p.Estado,
                        Productos = p.Productos
                    });

            return View(model);
        }

        public async Task<ActionResult> Actualizar(string id,string estado)
        {
            if(await pedidos.Actualizar(id, estado))
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> ActualizarCliente(string id,string estado)
        {
            if(await pedidos.Actualizar(id, estado))
            {
                return RedirectToAction("IndexCliente");
            }
            return RedirectToAction("IndexCliente");
        }
         public async Task<ActionResult> ActualizarReferencia(string id,string estado, string referencia)
        {
            //var userID = User.Identity.Name;
            if(await pedidos.ActualizarReferencia(id, "Sin Verificar", referencia))
            {
                return RedirectToAction("Referencia");
            }
            return RedirectToAction("Referencia");
        }

        public async Task<ActionResult> DamePedido(string id)
        {
            var model = await pedidos.LeerPedido(id);
            return View(new PedidoModel(){
                PedidoId = model.PedidoId,
                CorreoElectronico = model.CorreoElectronico,
                FechaPedido = model.FechaPedido,
                Referencia = model.Referencia,
                Estado = model.Estado,
                Productos = model.Productos
            });

        }

        public async Task<List<ProductoModel>> RegresaDetalle(string id)
        {
            var producto = await pedidos.LeerPedido(id);
            List<ProductoModel> list = JsonConvert.DeserializeObject<List<ProductoModel>>(producto.Productos);
            return list;
        }
        public async Task<ActionResult> Detalle(string x)
        {
            var y = new List<ProductoModel>();
            y = await RegresaDetalle(x);
            var model = (y)
            .Select(p => new ProductoModel(){
                id = p.id,
                Nombre = p.Nombre,
                Precio = p.Precio,
                Descripcion = p.Descripcion,
                Categoria = p.Categoria,
                Imagen = p.Imagen
            });
            return View(model);
        }
    }
}

Views/Shared/_CarritoPartial.cshtml
@inject TiendaMarvel.Services.CarritoService carritoService
<ul class="nav navbar-nav navbar-right">
    <li>
        <a asp-controller="Carrito" asp-action="Index">
            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">

            </span>
            @if(carritoService.NumeroDePartidas>0){
            <span class="badge">@carritoService.NumeroDePartidas</span>
            }
        </a>
    </li>

</ul>

Views/Shared/_Layout.cshtml
@inject ICategoriasRepository categorias
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<link rel="stylesheet" href="~/css/layouts.css" />
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TiendaMarvel</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @{
        var cates = await categorias.LeerTodas();
    }
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img class="" src="http://www.g33k-hq.com/wp-content/uploads/2013/10/thumbnail-marvel-character-logo-620x250.jpg" width="90" height="25"/>
                </a> 
            </div>
            <div class="navbar-collapse collapse" style="font-size:14px;">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @foreach(var c in cates){
                        <li><a asp-controller="Catalogo" asp-action="ProductosPorCategoria" asp-route-id="@c.Descripcion">@c.Descripcion</a></li>
                    }

                    @if(!User.IsInRole("Admin") && @UserManager.GetUserName(User) != null){
                        <li><a asp-area="" asp-controller="Solicitar" asp-action="IndexCliente" asp-route-id="@UserManager.GetUserName(User)">Pedidos</a></li>
                    }

                    @if(User.IsInRole("Admin") ){
                        <li><a asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a></li>
                        <li><a asp-area="" asp-controller="Catalogo" asp-action="Index">Productos</a></li>
                        <li><a asp-area="" asp-controller="Solicitar" asp-action="Index">Pedidos</a></li>
                    }
                    
                    
                </ul>
                
                @await Html.PartialAsync("_CarritoPartial")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div  class="cont">
        @RenderBody()
        <hr />
        <footer  class="redes">
            <p>&copy; 2018 - TiendaMarvel</p>
            <a href="https://www.facebook.com/" target="_blank"><img class="" src="https://upload.wikimedia.org/wikipedia/commons/c/c2/F_icon.svg" width="30" height="30" /></a>
            <a href="https://www.youtube.com/" target="_blank"><img class="" src="https://trinacriahealththerapy.com.au/wp-content/uploads/2017/03/YouTube_Play_Button.svg_.png" width="30" height="30" /></a>
            <a href="https://twitter.com/?lang=es" target="_blank"><img class="" src="https://vignette.wikia.nocookie.net/detective-conan/images/6/67/Twitter-logo.png/revision/latest?cb=20170828181017&path-prefix=es" width="30" height="30"/></a>
            <a href="https://www.instagram.com/?hl=es-la" target="_blank"><img class="" src="https://www.edigitalagency.com.au/wp-content/uploads/instagram-logo-png-transparent-background.png" width="30" height="30"/></a>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>